<?php
/***************************************************************************
 Extension Name	: Magento Navigation Menu Pro - Responsive Mega Menu / Accordion Menu / Smart Expand Menu
 Extension URL	: http://www.magebees.com/magento-navigation-menu-pro-responsive-mega-menu-accordion-menu-smart-expand.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/ 
?>
<?php $group_id = $this->getRequest()->getParam('id');?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('navigationmenupro')->__('Embeded Information') ?></h4>
    </div>
	<fieldset id="xml-info">
		<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><p><?php echo Mage::helper('navigationmenupro')->__('Insert Into Static Block Or CMS Page') ?></p></h4>
	</div>
		
	<fieldset id="template-tag">
<textarea id="navigationmenupro-template-tag" rows="2" cols="180" onclick="this.focus();this.select()" readonly="readonly">
&#123;&#123;block type="navigationmenupro/menucreator" name="menucreator_group_<?php echo $group_id;?>" group_id="<?php  echo $group_id ?>" template="navigationmenupro/menucreator.phtml" &#125;&#125;
</textarea>

		
	</fieldset>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('navigationmenupro')->__('Reference Via XML Layout File') ?></h4>
	</div>
		
	<fieldset id="xml-code">
		
		
<textarea id="navigationmenupro-code" rows="6" cols="180" onclick="this.focus();this.select()" readonly="readonly">
&lt;block type="navigationmenupro/menucreator" name="menucreator_group_<?php  echo $group_id ?>"
template="navigationmenupro/menucreator.phtml"&gt;
&lt;action method="setGroupId"&gt;&lt;value&gt;<?php  echo $group_id; ?>&lt;/value&gt;&lt;/action&gt;
&lt;action method="setCssJs"&gt;&lt;value&gt;<?php  echo $group_id; ?>&lt;/value&gt;&lt;/action&gt;
&lt;/block&gt;
</textarea>

		
	</fieldset>
</div>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('navigationmenupro')->__('Call Via Frontend Template File ') ?></h4>
	</div>
<fieldset id="xml-code">
<textarea id="navigationmenupro-template-code" rows="2" cols="180" onclick="this.focus();this.select()" readonly="readonly">
&lt;?php echo $this->getLayout()->createBlock("navigationmenupro/menucreator")->setGroup_id(<?php echo $group_id;?>)->setTemplate("navigationmenupro/menucreator.phtml")->toHtml();?&gt;
</textarea>
</fieldset>
</div>
	</fieldset>
</div>