<?php 

 /***************************************************************************
	Extension Name 	: Import Export Products Extension for Simple Products | Configurable Products | Bundle Products | Group    Products | Downloadable Products
	Extension URL   : http://www.magebees.com/magento-import-export-products-extension.html 
	Copyright  		: Copyright (c) 2015 MageBees, http://www.magebees.com
	Support Email   : support@magebees.com 
 ***************************************************************************/ 

?>
<style>
.docs-item{margin:1px;/* border:1px dotted black; */}
.docs-item h3{background:#666e73;color:white;padding:3px 3px 3px 10px;}
.docs-item ul{margin:10px}
.docs-item a {font-size: 14px;text-decoration: none;}	
.docs-item ul li{padding:10px 0 0 0}
</style>				
<div id="sample_csv_content">

<div class="docs-item">
<h3><?php echo $this->__("Documentation") ?></h3>
<ul class="docs-ul">
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-use-guide.pdf" target="_blank"><?php echo $this->__("How to Use Guide") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-bundle-products.pdf" target="_blank"><?php echo $this->__("How to Import Bundle Products") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-configurable-products.pdf" target="_blank"><?php echo $this->__("How to Import Configurable Products") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-downloadable-products.pdf" target="_blank"><?php echo $this->__("How to Import Downloadable Products") ?></a>
	</li>										
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-group-price.pdf" target="_blank"><?php echo $this->__("How to Import Group Price") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-group-products.pdf" target="_blank"><?php echo $this->__("How to Import Group Products") ?></a>
	</li>

	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-update-custom-option-store-wise.pdf" target="_blank"><?php echo $this->__("How to Update Custom Option Store wise") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/how-to-import-tier-price.pdf" target="_blank"><?php echo $this->__("How to Import Tier Price") ?></a>
	</li>
	<li>
		<a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-doc/troubleshooting.pdf" target="_blank"><?php echo $this->__("Troubleshooting") ?></a>
	</li>
</ul>	
</div>