<?php

 /***************************************************************************
	Extension Name 	: Import Export Products Extension for Simple Products | Configurable Products | Bundle Products | Group    Products | Downloadable Products
	Extension URL   : http://www.magebees.com/magento-import-export-products-extension.html 
	Copyright  		: Copyright (c) 2015 MageBees, http://www.magebees.com
	Support Email   : support@magebees.com 
 ***************************************************************************/ 

?>

<div id="messages">
<ul class="messages">
<li class="notice-msg">
		<ul>
			<li><?php echo $this->__('Note:- Generated CSV file is store in "var/import" folder and Images are store in "media/import" folder.')?></li>
		</ul>
	</li>
	<li class="notice-msg">
		<ul>
			<li><?php echo $this->__('Your server PHP settings not allow you to run script more than %s sec. at a time.', $this->getMaxExecutionTime())?></li>
			<li><?php echo $this->__('Your server PHP settings allow you to upload files not more than %s at a time. Please modify post_max_size (currently is %s) and upload_max_filesize (currently is %s) values in php.ini if you want to upload larger files.', $this->getDataMaxSize(), $this->getPostMaxSize(), $this->getUploadMaxSize())?></li>
		</ul>
	</li> 
	<li class="notice-msg">
		<ul>
			<li><?php echo $this->__('Make sure that data encoding in the file is consistent and saved in CSV (comma separated only) with supported encodings (UTF-8 or ANSI).')?></li>
		</ul>
	</li>
</ul>
</div> 
<form action="<?php echo  Mage::helper("adminhtml")->getUrl("adminhtml/downloadimages/uploadProfile/");?>" method="post" enctype="multipart/form-data">
	<legend><?php echo $this->__("Upload File") ?></legend>
	<fieldset>
		<table height="80">
		<tr>
			<td>
				<label for="downloadimg"><?php echo $this->__("Select your CSV (Comma delimited) File :") ?></label>
			</td>
			<td>
				<input type="file" class="required-entry required-entry" id="downloadimg" name="downloadimg"  />
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"  />
			</td>
		</tr>
		<tr>
			<td></td>
			<td>							
				<button style="" onclick="return valid(true)" class="scalable save" type="submit" title="Run Profile in Popup" ><span><?php echo $this->__("Download Images and Generate csv") ?></span></button>
			</td>
		</tr>
		</table>							
	</fieldset>
</form>

<style>
.sample-csv-item{margin:1px;}
.sample-csv-item h4{background:#666e73;color:white;padding:3px 3px 3px 10px;}
.sample-csv-item ul{margin:10px}
.sample-csv-item a {font-size: 14px;text-decoration: none;}				
</style>				
<div id="sample_csv_content">
	<div class="sample-csv-item">
		<h4><?php echo $this->__("Sample CSV for Download Images from Live URL") ?></h4>
			<ul class="sample-csv-ul">
				<li> <a href="http://www.magebees.com/media/mconnect_uploadfiles/import-export-products-csv/download_images_sample.csv"> <?php echo $this->__("Download Sample csv File") ?> </a> </li>
			</ul>
	</div>
</div>
<script>
	function valid(){
		var name=document.getElementById('downloadimg').value;
		if(name==""){
			alert("Please upload the file first.");
			return false;
		}else{
			Element.show('loading-mask');
		}
	}
</script>