<style>
.notes-body {
	position: relative;
    font-size: 11px;
    padding: 10px;
    border: 1px solid #f1f5fc;
    box-shadow: 0 1px 1px rgba(0,0,0,.5);
    -moz-box-shadow: 0 1px 1px rgba(0,0,0,.5);
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.5);
        background: #fff;
}

.masoitems-text {
		padding: 10px;
		background: #fff;
		border-left: 2px solid #ff9933;
		margin-bottom: 10px;
}
</style>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Add To Cart From CSV');?></h1>    
</div>

<?php $t = Mage::getStoreConfig('mascartaddcsv/customer/text_above');?>
<?php if ($t != ''):?>
	<div class="masoitems-text"><?php echo $t?></div>
<?php endif;?>
<div class="block">
	<div class="block-content">
		<form action="<?php echo $this->getUrl('mascartaddcsv/index/process')?>" method="POST" enctype="multipart/form-data">
			<div id="uploadCSV" class="notes-body">
				<input type="file" name="file" />
			</div>
			<div class="actions">
				<button type="submit" class="button"><span><span><?php echo $this->__('Add To Cart')?></span></span></button>
			</div>
		</form>
	</div>
</div>