<script type="text/javascript">
  jQuery.noConflict(); //Use no conflict here instead of js file
  
</script>
<?php

	$enable_disable = Mage::helper("navigationmenupro")->isEnabled();
	
	
	if($enable_disable == "1") {
	$groupId = $this->getGroupId();
	$menu_status = $this->getMenuStatus($groupId);
	$menu_type = $this->getMenutype($groupId);
	
	if($menu_status=="1"){
		$responsive_breakpoint = $this->getBreakPoint($groupId);
		$hover_delay = $this->getHoverOptions($groupId);
		
		if($responsive_breakpoint==""){
			$responsive_breakpoint = '768px';
		}
		if($menu_type!="list-item"){
		$filename = $menu_type."-".$groupId;
?><link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/navigationmenupro/'.$filename.'.css');?>" media="all" />
<?php
		}
	$menu_customer = Mage::getModel('navigationmenupro/customer');
	$permission = $menu_customer->getUserPermission();
	
	$developer_mode_enable_disable = Mage::helper("navigationmenupro")->isDevelopmentEnabled();
	if($developer_mode_enable_disable == "1") {
		echo $menu_html = Mage::helper("navigationmenupro")->get_menu_items($groupId);
	}else
	{
		echo $menu_html = Mage::helper("navigationmenupro")->getStaticMenu($groupId);
	}
	?>
<script type="text/javascript">
var responsive = '<?php echo str_replace("px","",$responsive_breakpoint);?>';

	

	jQuery(window).on('load resize', function() {
		if (jQuery(window).width() > responsive ) {
			var timeoutId;
			jQuery('#cwsMenu-<?php echo $groupId;?> > ul.cwsMenu > li.parent').hover(function() {
				var self = this;
                if (!timeoutId) {
					timeoutId = window.setTimeout(function() {
						timeoutId = null;
						jQuery(self).children("ul").stop().slideDown('<?php echo $hover_delay['slidedown']; ?>');
					}, '<?php echo $hover_delay['hoverdelay']; ?>');
				}
			},
			function () {
				if (timeoutId) {
					window.clearTimeout(timeoutId);
					timeoutId = null;
				} else {
					jQuery(this).children("ul").stop().slideUp('<?php echo $hover_delay['slideup']; ?>');
				}
			});
		}
	});


jQuery(document).ready(function() {
	var group_id = '#cwsMenu-<?php echo $groupId;?>';
	var menu = '<?php echo $menu_type;?>';
	var responsive = '<?php echo $responsive_breakpoint;?>';
	init(group_id,menu,responsive);
		/*jQuery('#cwsMenu-<?php echo $groupId;?>').cwsmenu({
				group_id : '#cwsMenu-<?php echo $groupId;?>',
				menu_type:'<?php echo $menu_type; ?>',
				responsive_breakpoint:'<?php echo $responsive_breakpoint;?>',
		});	*/
	}); 

</script>
<?php 
}
}
?>
