<?php
/***************************************************************************
 Extension Name	: Magento Navigation Menu Pro - Responsive Mega Menu / Accordion Menu / Smart Expand Menu
 Extension URL	: http://www.magebees.com/magento-navigation-menu-pro-responsive-mega-menu-accordion-menu-smart-expand.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/ 
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('navigationmenupro/js/jquery.min_1.11.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('navigationmenupro/js/jquery-ui.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('navigationmenupro/js/jquery.mjs.nestedSortable.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('navigationmenupro/jscolor/jscolor.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('navigationmenupro/js/menugridcustom.js'); ?>"></script>
</head>
<script>
jQuery(document).ready(function() {
	jQuery("#navigation-pro").menugrid();
});
</script>
<body>
      <div id="button1"></div>
	  <div id="button2"></div>
<div class="content-header">
	<h3><?php echo $this->__('Manage Menu Items')?></h3>
	
</div>
<div id="page:main-container">
	<div id="navigation-pro">
		<div class="columns">
			<div id="page:left" class="side-col">
			<p class="switcher">
				<?php $store_swatcher = Mage::helper('navigationmenupro')->getstore_swatcher();?>
				<label for="store_switcher">Choose Store View </label>
				<select id="store_switcher" name="store_switcher">
					<?php 
						foreach($store_swatcher as $value){
						if($value['value']==0){
						?>
						<option value="0"><?php echo $value['label']; ?></option>
					<?php } else { ?>
						<optgroup label="<?php echo $value['label']; ?>"></optgroup>
					<?php
				if(!empty($value['value'])){
						foreach ($value['value'] as $option){
							?>
					<option value="<?php echo $option['value']; ?>"><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;".$option['label'];?></option>
					<?php 
						}
					}
				}
				}
				?>
				</select>
				</p>
				<?php 
 			$menu_backend = $this->group_menu_tree();
			echo $menu_backend;
 ?>
				<div id="deletedialog" style="display:none;">
					<form class="deletemenuitem-form" action="#" id="deletemenuitem">
						<span class="deleteMenu ui-icon ui-icon-closethick" title="Close"><span></span></span>
						<h3>Delete Menu Item Options</h3>
						<input type="radio" id="deleteparent"  name="deleteoption" value="deleteparent" checked="checked">
						<label for="deleteparent">Delete Parent Menu Item Only </label>
						<br/>
						<br/>
						<input type="radio" id="deleteparentchild" name="deleteoption" value="deleteparentchild">
						<label for="deleteparentchild">Delete Parent And Child Both Menu Items</label>
						<br/>
						<br/>
						<input type="button" id="deleteitem" name="deleteitem" value="Delete"/>
						<input type="button" id="cancelitem" name="cancelitem" value="Cancel" />
						<br/>
					</form>
				</div>
				<div id="footerBut">
				<?php $url = Mage::helper("adminhtml")->getUrl("adminhtml/menucreator/updateMenu");?>
					<button id="saveorder" name="saveorder" class="scalable save " type="button" title="SaveOrder" data-saveOrder-url="<?php echo $url;?>"><span>SaveOrder</span></button>
					<button style="" id="expandall" name="expanded" class="scalable " type="button" title="Expand All"><span><span><span>Expand All</span></span></span></button>
					<button style="" id="collapsed" name="expanded" class="scalable " type="button" title="Collapse All"><span><span><span>Collapse All</span></span></span></button>
				</div>
				
				
			</div>
			<div class="main-col" id="content">
			
			<p class="form-buttons">
					<button style="" id="add_new_btn" class="action primary" type="button" title="Add New"><span>Add New</span></button>
					<button style="" id="save_btn" class="scalable save" type="button" title="Save Menu Item"><span>Save</span></button>
					
					
					<button style="" id="cancel_btn" class="action primary " type="button" title="Cancel"><span>Cancel</span></button>
					</p>
			
				<div class="main-col-inner">
					<form id="edit_form"  method="post" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/menucreator/save/");?>" enctype="multipart/form-data" >
						<?php 
						$menuType = Mage::helper('navigationmenupro')->getallMenuTypes();
						$getallLink = Mage::helper('navigationmenupro')->getallLinks();
						 ?>
						<div class="sticky-content-header">
							<h3 align="center">
								<p id="menu_title">Create New Menu Item</p>
							</h3>
						</div>
						<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
						<input type="hidden" value="" name="menu_id" id="menu_id">
						<input name="current_menu_id" id="current_menu_id" type="hidden"/>
						<input type="hidden" name="image_path" id="image_path" value="<?php echo Mage::getBaseUrl('media')."navigationmenupro/image/";?>"/>
						<div id="menucreator-tabs">
							<ul>
								<li><a href="#general-option">General Options</a></li>
								<li><a href="#advance-option">Advance Options</a></li>
								<li><a href="#label-option">Label Options</a></li>
							</ul>
							<div id="general-option">
								<ul class="fieldSet">
									<li class="fields">
										<div class="field">
											<label class="label required-label" data-toggle="tooltip" data-placement="bottom" title="The type of link: CMS Page, Category Page, Form ...">Menu Item Type <em>*</em></label>
											<select id="type" name="type" class="required-entry select">
												<option value="">Select Menu type</option>
												<optgroup label="Top url types">
												<?php foreach($menuType as $key => $value):?>
												<option value="<?php echo $key;?>"><?php echo $value;?></option>
												<?php endforeach;?>
												</optgroup>
												<optgroup label="Mosted Used Links">
												<?php foreach($getallLink as $key => $value):?>
												<option value="<?php echo $key;?>"><?php echo $value;?></option>
												<?php endforeach;?>
												</optgroup>
											</select>
										</div>
										<div class="field">
											<label class="label required-label" title="">Status</label>
											<select id="status" class="required-entry select" name="status">
												<?php 
													$menu_status = Mage::getModel('navigationmenupro/status')->getOptionArray();
													foreach ($menu_status as $key => $status) {
														echo "<option value='".$key."'>".$status."</option>";
													}
												?>
											</select>
										</div>
									</li>
									<li class="fields column3" id="category_content" style="display:none;">
										<div class="field">
											<label class="label required-label" data-toggle="tooltip" data-placement = "bottom" title="The type of link: CMS Page, Category Page, Form ...">Select Category <em>*</em></label>
											<select id="category_id"  disable="true" name="category_id" class="required-entry">
												<option value="">Select Category</option>
												<?php 
													$categories = Mage::getModel('catalog/category')->getCollection()
														->addAttributeToSelect('*')
														->addAttributeToFilter('level', 1)
														->addAttributeToFilter('is_active', 1);
													$parent_categories = $categories->getData();
													foreach($parent_categories as $key => $value):
													$category_list[$value['entity_id']] = $this->getTreeCategories($value['entity_id'],true);
													$parent_category = Mage::getModel('catalog/category')->load($value['entity_id']);
													$Categories_list = Mage::getModel("navigationmenupro/menucreator")->getCategorieslist($value['entity_id'],true);
													if($Categories_list != ''){
														echo "<optgroup label=".$parent_category->getName()."><option value=".$parent_category->getId().">".$parent_category->getName()."</option>";
														echo $Categories_list;
														echo "</optgroup>";
													}
													endforeach;
												?>
											</select>
										</div>
										
										<div class="field" id="category_image_type" style="display:none;">
											<label class="label">Show Category Image</label>
											<select  name="image_type" id="image_type">
											<?php $magentoVersion = Mage::getVersion();
												if (version_compare($magentoVersion, '1.9.1.0', '>=')){
												?>
												<option value = "none">None</option>
												<option value = "main_image">Show category image in menu</option>
												<?php
												} 
												else {
												?>
												<option value = "none">None</option>
												<option value = "thumbnail_image">Show category thumbnail image in menu</option>
												<option value = "main_image">Show category image in menu</option>
												<?php
												}?>
											</select>
										</div>
										<div class="field" id="category_content_option" style="display:none;">
											<label for="autosub"><input type="checkbox" disable="true" value="0" onclick="this.value = this.checked ? 1 : 0;" value="" name="autosub" id="autosub"> Show Auto Sub-Categories</label><br />
											<label for="autosubimage"><input type="checkbox" disable="true" value="0" onclick="this.value = this.checked ? 1 : 0;" value="" name="autosubimage" id="autosubimage"> Show Images For Sub-Categories</label><br />
											<label for="customimage"><input type="checkbox" disable="true" value="0" onclick="this.value = this.checked ? 1 : 0;" value="" name="show_custom_category_image" id="customimage"> Use Custom Image For Main Category</label><br />
											
										</div>
									</li>
									<li class="fields" id="select_cms_pages" style="display:none;">
										<div class="field">
											<label class="control-label required-label"  title="">Select Cms Pages <em>*</em></label>
											
											<?php 
											$cms_pages_collection = Mage::getModel('cms/page')->getCollection();
												$cms_page_sort    = array();
												foreach($cms_pages_collection as $cms_key => $cms_value):
													if($cms_value->getIsActive() == "1")
													{
													$cms_page_sort[$cms_value->getTitle()][] = $cms_value->getData();
												   }
												endforeach;
												ksort($cms_page_sort);
										?>
										<select id="cmspage_identifier" name="cmspage_identifier" disable="true" class="required-entry select">
												<option value=''>Please Select Cms Page</option>
												<?php
													$cms_pages_collection = Mage::getModel('cms/page')->getCollection();
													foreach($cms_page_sort as $cms_key => $cms_value):
													if($cms_value['0']['is_active']== "1")
													{
												?>
													<option value="<?php echo $cms_value['0']['identifier'];?>"><?php echo $cms_value['0']['title'];?></option>
												<?php 
												}endforeach;
												?>
											</select>
										</div>
										
									</li>
									
									<li class="fields" id="select_static_block" style="display:none;">
										<div class="field" >
											<label class="control-label required-label"  title="">Select Static Block <em>*</em></label>
											
											<?php 
											$static_block_collection = Mage::getModel('cms/block')->getCollection();
													$static_block_sort    = array();
												foreach($static_block_collection as $static_key => $static_value):
													if($static_value->getIsActive() == "1")
													{
													$static_block_sort[$static_value->getTitle()][] = $static_value->getData();
												    }
												endforeach;
												ksort($static_block_sort);
											?>
											<select id="staticblock_identifier" disable="true" name="staticblock_identifier" class="required-entry select" >
												<option value=''>Please Select Static Block</option>
												<?php
													foreach($static_block_sort as $static_key => $static_value):
													if($static_value['0']['is_active']== "1")
													{
												?>
													<option value="<?php echo $static_value['0']['identifier'];?>"><?php echo $static_value['0']['title'];?></option>
												<?php 
												}endforeach;
												?>
											</select>
										</div>
										<div class="field" id="show_hide_menu_title" style="display:none;">
											<label class="control-label required-label"  title="">Show / Hide Menu Title <em>*</em></label>
											<select id="title_show_hide" disable="true" name="title_show_hide"class="required-entry select">
												<option value=''>Please Select Show / Hide Menu Title</option>
												<option value='show'>Show</option>
												<option value='hide'>Hide</option>
											</select>
										</div>
										</li>
										
									<li class="fields" id="product_page" style="display:none;">
										<div class="field">
											<label class="control-label required-label"  title="">Product Id <em>*</em></label>
											<input type="text" id="product_id" disable="true" value="" name="product_id" class="required-entry input-text validate-digits" placeholder="Enter product id..." />
										</div>
									</li>
									<li class="fields" id="custom_url" style="display:none;">
										<div class="field">
											<label class="control-label required-label"  title="">Custom Url <em>*</em></label>
											<input type="text" id="url_value" value="" disable="true" name="url_value" class="required-entry input-text" placeholder="Enter url here..." />
										</div>
										<!-- validate-url  -->
										<div class="field" id="custom_link_content_option" style="display:block;">
										<label for="useexternalurl"><input type="checkbox" disable="true" value="0" name="useexternalurl" id="useexternalurl"> External URL </label>
											<br />
											(Ex: http://www.example.com)
										</div>
									</li>
									<li class="fields" id="menu_title_check">
										<div class="field">
											<label class="control-label required-label"  title="">Menu Title <em>*</em></label>
											<input type="text" id="title" name="title"  class="span3 required-entry input-text" placeholder="Enter title here..." />
										</div>
										<div class="field">
											<label class="label" title="">Add Custom Class</label>
											<input type="text" id="class_subfix" name="class_subfix" class="input-text" placeholder="Enter class name" />
										</div>
									</li>
									<li class="fields">
										<div class="field required-entry" id="group_id_content">
											<label title="" class="label required-label">Assign Menu Group <em>*</em></label>
											<?php $url = Mage::helper('adminhtml')->getUrl('adminhtml/menudata/parent');?>
											<input type="hidden" name="parent_url" id="parent_url" value="<?php echo $url;?>"/>
											<select id="group_id" class="required-entry select" name="group_id"  data-parenturl="<?php echo $url;?>">
												<?php 
													$groupData = Mage::getModel('navigationmenupro/menucreatorgroup')->getAllGroup();
													foreach ($groupData as $group) {
														echo "<option value='".$group['value']."'>".$group['label']."</option>";
													}
												?>
											</select>
										</div>
										<div class="field required-entry" id="parent_id_content">
											<label class="label required-label"  title="">Parent Item <em>*</em></label>
											<select id="parent_id" class="required-entry select" name="parent_id">
												<option value="">Please Select Parent</option>
												<option value="0">Root</option>
											</select>
										</div>
									</li>
									<li class="fields">
										<div class="field required-entry">
											<label class="label required-label"  title="">Visible In <em>*</em></label>
											<select id="storeids" name="storeids[]" multiple="multiple" class="required-entry">
												<?php 
													foreach($store_swatcher as $value){
													if($value['value']==0){
												?>
													<option value="0"><?php echo $value['label']; ?></option>
												<?php
													} else { ?>
													<optgroup label="<?php echo $value['label']; ?>"></optgroup>
												<?php
													if(!empty($value['value'])){
														foreach ($value['value'] as $option){
												?>
													<option value="<?php echo $option['value']; ?>"><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;".$option['label'];?></option>
												<?php 
													}
													}
													}
													}
												?>
											</select>
										</div>
									</li>
									<li class="fields">
										<div class="field" id="subcolumn">
											<label class="control-label required-label"  title="">Sub Column Layout <em>*</em></label>
											<select name="subcolumnlayout" class="required-entry select" id="subcolumnlayout">
												<?php 
													$column_layout = Mage::helper('navigationmenupro')->columnLayout();
													foreach ($column_layout as $key => $layout) {
														echo "<option value='".$key."'>".$layout."</option>";
													}
												?>
											</select>
										</div>
										<div class="field" id="text_align_content">
											<label class="control-label"  title="">Sub Menu Align <em>*</em></label>
											<select name="text_align" id="text_align">
												<?php 
													$alignment = Mage::helper('navigationmenupro')->getAlignment();
													foreach ($alignment as $key => $layout) {
														echo "<option value='".$key."'>".$layout."</option>";
													}
												?>
											</select>
										</div>
									</li>
								</ul>
							</div>
							<div id="advance-option">
								<ul class="fieldSet">
									<li class="fields">
										<div class="field">
											<label class="label" title="">Access Permission</label>
											<select id="permission" name="permission">
												<?php 
													$permissions = Mage::helper('navigationmenupro')->getPermission();
													foreach ($permissions as $permissions) {
														echo "<option value='".$permissions['value']."'>".$permissions['label']."</option>";
													}
												?>
											</select>
										</div>
										<div class="field">
											<label class="label">Target Window</label>
											<select id="target" name="target">
												<option value="1">Parent</option>
												<option value="2">New Window</option>
											</select>
										</div>
									</li>
									<li class="fields">
										<div class="field">
											<label class="label">Custom Link Title <span style="padding-right:10px"></span> </label>
											<input type="text" id="description" name="description" class="input-text" placeholder="Custom item title for SEO ...">
										</div>
									</li>
									<li class="fields">
										<div class="field">
											<label class="label" title="">Set Relation {For Example : rel="nofollow noreferrer"}</label>
											<select id="setrel" name="setrel[]" multiple>
												<?php 
													$relations = Mage::helper('navigationmenupro')->getRelation();
													foreach ($relations as $relation) {
														echo "<option value='".$relation['value']."'>".$relation['label']."</option>";
													}
												?>
											</select>
										</div>
									</li>
									<li class="fields">
										<div class="field" id="image_upload">
											<label class="label"  title="">Upload Item Thumbnail</label>
											<input type="file" class="input-file input-text" value="" name="image" id="image">
										</div>
										<div class="field" id="image_upload_show_hide">
											<label class="label"  title="">Show/Hide Thumbnail</label>
											<select name="image_status" id="image_status" style="height:auto;">
												<option value="0">Please select</option>
												<option value="1">Show</option>
												<option value="2">Hide</option>
											</select>
										</div>
									</li>
								</ul>
							</div>
							<div id="label-option">
					<ul class="fieldSet">
						<li class="fields">
							<div class="field">
								<label class="label">Label Title <span style="padding-right:10px"></span> </label>
								<input type="text" id="label_title" name="label_title" class="input-text" placeholder="Label Title...">
							</div>
							<div class="field" id="label_height">
								<label class="label"  title="">Label Font Size</label>
								<input type="text" class="input-file input-text" value="9px" name="height" id="height" placeholder="In Px ..">
							</div>
							
						</li>
						<li class="fields">
							<div class="field" id="label_bg_color">
								<label class="label"  title="">Label Text Color</label>
								<input type="text" class="input-file input-text color" value="#FFFF00" name="label_text_color" id="label_text_color">
							</div>
							<div class="field" id="label_color">
								<label class="label"  title="">Label Text Background  Color</label>
								<input type="text" class="input-file input-text color" value="#db0000" name="label_text_bg_color" id="label_text_bg_color">
							</div>
							
						</li>
					</ul>
				</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</div>
<script>
var editForm = new varienForm('edit_form', '');
editForm.submit = function(button, url) {
                if (this.validator.validate()) {
					//var form = this.form;
					var form = document.getElementById("edit_form"); 
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        form.submit();
						
                    } catch (e) {
                    }
                    form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
					if(jQuery("#ui-id-1").hasClass('error'))
					{
					jQuery("#ui-id-1").removeClass("error");
					}
                }else
				{
				jQuery('#menucreator-tabs').tabs({
				active: 0
				});
				if(!jQuery("#ui-id-1").hasClass('error'))
				{
				jQuery("#ui-id-1").addClass("error");
				}
				}
            }.bind(editForm);
</script>