<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Stockstatus
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()):
    if ($_item->getData('child_product_id')) {
        $productId = $_item->getData('child_product_id');
    } else {
        $productId = $_item->getProductId();
    }

    // BEGIN: MageWorx Admin Order Editor (MageWorx_OrdersEdit) compatibility
    if (Mage::helper('amstockstatus')->isOrderEditEnabled()) {
        // code from: Magento_root/app/design/adminhtml/default/default/template/mageworx/ordersedit/sales-items-column-name.phtml
        $imgHelper = $this->helper('mageworx_ordersedit')->getImgByItem($_item);
        if ($imgHelper) { ?>
            <a href="<?php echo $imgHelper ?>" rel="mageworxLightbox[]">
                <img src="<?php echo $imgHelper->resize(90, 90); ?>" height="90" alt="" align="left"
                     style="padding-right:2px;"/>
            </a>
        <?php } else { ?>
            <img src="<?php echo Mage::getDesign()->getSkinUrl('images/placeholder/thumbnail.jpg'); ?>" height="90"
                 width="90" alt="" align="left" style="padding-right:2px;"/>
        <?php }
    }
    // END: MageWorx Admin Order Editor (MageWorx_OrdersEdit) compatibility

    $status = Mage::helper('amstockstatus')->getStockStatusFromHistory($_item->getOrder()->getIncrementId(), $productId);
    ?>
    <h5 class="title"><span
                id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->escapeHtml($_item->getName()) . $status ?></span>
    </h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>
            :</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getSku()))); ?>
    </div>
    <?php if ($this->getOrderOptions()): ?>
    <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?></dt>
            <dd>
                <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                    <?php echo $this->getCustomizedOptionValue($_option); ?>
                <?php else: ?>
                    <?php $_option = $this->getFormattedOption($_option['value']); ?>
                    <?php echo $_option['value']; ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                        <span id="<?php echo $_dots = 'dots' . uniqid() ?>"> ...</span><span
                                id="<?php echo $_id = 'id' . uniqid() ?>"><?php echo $_option['remainder'] ?></span>
                        <script type="text/javascript">
                            $('<?php echo $_id ?>').hide();
                            $('<?php echo $_id ?>').up().observe('mouseover', function () {
                                $('<?php echo $_id ?>').show();
                            });
                            $('<?php echo $_id ?>').up().observe('mouseover', function () {
                                $('<?php echo $_dots?>').hide();
                            });
                            $('<?php echo $_id ?>').up().observe('mouseout', function () {
                                $('<?php echo $_id ?>').hide();
                            });
                            $('<?php echo $_id ?>').up().observe('mouseout', function () {
                                $('<?php echo $_dots ?>').show();
                            });
                        </script>
                    <?php endif; ?>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
    <?php echo $this->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
