<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
<td class="label">
    <label><?php echo $this->__('Options') ?></label>
</td>
<td class="value">
    <div class="grid" id="options">
        <table cellpadding="0" cellspacing="0" class="border">
            <tbody>
            <tr class="headings" id="headings<?php echo $_htmlId ?>" style="display: none;">
                <td colspan="2"></td>
            </tr>
            <tr id="addRow<?php echo $_htmlId ?>" style="display: none;">
                <td colspan="1"></td>
                <td>
                    <button style="" onclick="" class="scalable add" type="button" id="addToEndBtn<?php echo $_htmlId ?>">
                        <span><span><span><?php echo $this->__('Add Option') ?></span></span></span>
                    </button>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
    <div id="empty<?php echo $_htmlId ?>">
        <button style="" onclick="" class="scalable add" type="button" id="emptyAddBtn<?php echo $_htmlId ?>">
            <span><span><span><?php echo $this->__('Add Option') ?></span></span></span>
        </button>
    </div>
</td>


<script type="text/javascript">
    var arrayRow<?php echo $_htmlId ?> = {
        template : new Template(
            '<tr id="#{_id}">'
            +'<td>'
            +'<input type="text" name="<?php echo $this->getElement()->getName() . '[#{_id}]' ?>" value="#{option}" />'
            +'<\/td>'
            <?php if ($this->_addAfter):?>
            +'<td><button onclick="" class="scalable add" type="button" id="addAfterBtn#{_id}"><span><span><span><?php echo Mage::helper('adminhtml')->__('Add after') ?><\/span><\/span><\/span><\/button><\/td>'
            <?php endif;?>
            +'<td><button onclick="arrayRow<?php echo $_htmlId ?>.del(\'#{_id}\')" class="scalable delete" type="button"><span><span><span><?php echo Mage::helper('adminhtml')->__('Delete') ?><\/span><\/span><\/span><\/button><\/td>'
            +'<\/tr>'
        ),
        rowsCount : 0,
        add : function(templateData, insertAfterId)
        {
            if ('' == templateData) {
                var d = new Date();
                var templateData = {
                    option: '',
                    _id : '_' + d.getTime() + '_' + d.getMilliseconds()
                };
            }
            if ('' == insertAfterId) {
                Element.insert($('addRow<?php echo $_htmlId ?>'), {before: this.template.evaluate(templateData)});
            } else {
                Element.insert($(insertAfterId), {after: this.template.evaluate(templateData)});
            }
            this.rowsCount += 1;
        },
        del : function(rowId)
        {
            $(rowId).remove();
            this.rowsCount -= 1;
            if (0 == this.rowsCount) {
                this.showButtonOnly();
            }
        },

        showButtonOnly : function()
        {
            //$('options').hide();
            $('empty<?php echo $_htmlId ?>').show();
        }
    }

    $('empty<?php echo $_htmlId ?>').hide();
    Event.observe('emptyAddBtn<?php echo $_htmlId ?>', 'click', function () {
        $('options').show();
        $('empty<?php echo $_htmlId ?>').show();
        arrayRow<?php echo $_htmlId ?>.add('', '');
    });


    <?php
        $_addAfterId = "headings{$_htmlId}";
        foreach ($this->getElement()->getValue() as $_rowId => $_row) {
            echo "arrayRow{$_htmlId}.add(" . json_encode(array('_id' => $_rowId, 'option' => $_row)) . ", '{$_addAfterId}');\n";
            $_addAfterId = $_rowId;
        }
    ?>

    arrayRow<?php echo $_htmlId ?>.showButtonOnly();

</script>
