<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
<style type="text/css">
    .shipping-service-list td.label,
    .shipping-service-list td.label label {
        width: 100px;
    }
    .shipping-service-list td.value select,
    .shipping-service-list td.value input.input-text {
        width: auto;
        min-width: 150px;
    }
</style>
<td class="label">
    <label><?php echo $this->__('Options') ?></label>
</td>
<td class="value">
    <div class="grid" id="options">
        <table cellpadding="0" cellspacing="0" class="border">
            <tbody>
                <tr class="headings" id="headings<?php echo $_htmlId ?>" style="display: none;">
                    <td colspan="2"></td>
                </tr>

                <!-- all goes here -->

                <tr id="addRow<?php echo $_htmlId ?>" style="display: none;">
                    <td colspan="1"></td>
                    <td>
                        <button style="" onclick="" class="scalable add" type="button" id="addToEndBtn<?php echo $_htmlId ?>">
                            <span><span><span><?php echo $this->__('Add Option') ?></span></span></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    <div id="empty<?php echo $_htmlId ?>">
        <button style="" onclick="" class="scalable add" type="button" id="emptyAddBtn<?php echo $_htmlId ?>">
            <span><span><span><?php echo $this->__('Add Option') ?></span></span></span>
        </button>
    </div>
</td>

<?php $shippingService = Mage::getModel('emjainteractive_shippingoption/option')->load('shipping_method', 'code'); ?>
<script type="text/javascript">
    var arrayRow<?php echo $_htmlId ?> = {
        template: new Template(
            '<tr id="#{_id}">'
            + '<td>'
            + '<div class="fieldset">'
            + '<table class="form-list shipping-service-list" style="margin-top: 15px;">'
            + '<tbody>'
            + '<tr>'
            + '<td class="label"><label><?php echo $this->__('Service Name') ?><\/label><\/td>'
            + '<td class="value"><input type="text" name="<?php echo $this->getElement()->getName() . '[#{_id}][name]' ?>" value="#{name}" class="input-text" \/><\/td>'
            + '<\/tr>'
            + '<tr>'
            + '<td class="label"><label><?php echo $this->__('Shipping Methods') ?><\/label><\/td>'
            + '<td class="value">'
            + '<select class="select" multiple="multiple" name="<?php echo $this->getElement()->getName() . '[#{_id}][carrier][]' ?>">'
            <?php if ($shippingService && $shippingService->getOptions()) : ?>
            <?php foreach ($shippingService->getOptions() as $option) : ?>
            +'<option value="<?php echo $this->jsQuoteEscape($option) ?>" #{<?php echo md5($option) ?>}><?php echo $this->jsQuoteEscape($option) ?><\/option>'
            <?php endforeach; ?>
            <?php endif; ?>
            + '<\/select>'
            + '<\/td>'
            + '<\/tr>'
            + '<\/tbody>'
            + '<\/table>'
            + '<\/div>'
            + '<\/td>'
            + '<td>'
            + '<button onclick="arrayRow<?php echo $_htmlId ?>.del(\'#{_id}\')" class="scalable delete" type="button"><span><span><span><?php echo Mage::helper('adminhtml')->__('Delete') ?><\/span><\/span><\/span><\/button>'
            + '<\/td>'
            + '<\/tr>'
        ),
        rowsCount : 0,
        add : function(templateData, insertAfterId)
        {
            if ('' == templateData) {
                var d = new Date();
                var templateData = {
                    option: '',
                    _id : '_' + d.getTime() + '_' + d.getMilliseconds()
                };
            }
            if ('' == insertAfterId) {
                Element.insert($('addRow<?php echo $_htmlId ?>'), {before: this.template.evaluate(templateData)});
            } else {
                Element.insert($(insertAfterId), {after: this.template.evaluate(templateData)});
            }
            this.rowsCount += 1;
        },
        del : function(rowId)
        {
            $(rowId).remove();
            this.rowsCount -= 1;
            if (0 == this.rowsCount) {
                this.showButtonOnly();
            }
        },

        showButtonOnly : function()
        {
            //$('options').hide();
            $('empty<?php echo $_htmlId ?>').show();
        }
    }
    $('empty<?php echo $_htmlId ?>').hide();
    Event.observe('emptyAddBtn<?php echo $_htmlId ?>', 'click', function () {
        $('options').show();
        $('empty<?php echo $_htmlId ?>').show();
        arrayRow<?php echo $_htmlId ?>.add('', '');
    });


    <?php
        $_addAfterId = "headings{$_htmlId}";
        $i = 0;
        foreach ($this->getElement()->getValue() as $_rowId => $_row) {
             $data = array(
                '_id' => $i,
                'name' => $_rowId,
             );
             foreach ($_row as $_r) {
                $data[md5($_r)] = 'selected="selected"';
             }
            echo "arrayRow{$_htmlId}.add(" . json_encode($data) . ", '{$_addAfterId}');\n";
            $_addAfterId = $id;
            $i++;
        }
    ?>

    arrayRow<?php echo $_htmlId ?>.showButtonOnly();
</script>
