<?php 
if($crumbs && is_array($crumbs)): ?>
<div class="col-sm-12 a-left">
    <ul>
        <?php $_product= Mage::registry('current_product');

	if(count($crumbs)<=2) { 
		if($_product){
			$cats = $_product->getCategoryIds();
			//foreach ($cats as $catId): ?>
				<?php $_cat = Mage::getModel('catalog/category')->load($cats[0]); ?>
                <?php
                $parentPath = explode('/', $_cat->getPath());
                $parentPath = array_splice($parentPath, 2);
                ?><br>
                <li class="home"><a href="<?php echo Mage::getBaseUrl() ?>" title="Go to Home Page">Home</a><span class="breadcrumbs-split"><i class="icon-right-open"></i></span></li>
                <?php foreach ($parentPath as $parentId): ?>
				<?php $_prentCat = Mage::getModel('catalog/category')->load($parentId); ?>
					<li class="breadcrumbs"><a href="<?php echo $_prentCat->getUrl() ?>"><?php echo $_prentCat->getName() ?></a>
					</li><span class="breadcrumbs-split"><i class="icon-right-open"></i></span>
				<?php endforeach ?>
                <li class="breadcrumbs"><strong><?php echo $_product->getName() ?></strong></li>
			<?php //endforeach; ?>
	<?php
		}	
		else { 
			foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
				<li class="<?php echo $_crumbName ?>">
				<?php if($_crumbInfo['link']): ?>
					<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
				<?php elseif($_crumbInfo['last']): ?>
                <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
				<?php else: ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
				<?php endif; ?>
				<?php if(!$_crumbInfo['last']): ?>
					<span class="breadcrumbs-split"><i class="icon-right-open"></i></span>
				<?php endif; ?>
				</li>
			<?php endforeach;  
		}   
	}  else { 
			foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
				<li class="<?php echo $_crumbName ?>">
				<?php if($_crumbInfo['link']): ?>
					<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
				<?php elseif($_crumbInfo['last']): ?>
					<strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
				<?php else: ?>
					<?php echo $this->escapeHtml($_crumbInfo['label']) ?>
				<?php endif; ?>
				<?php if(!$_crumbInfo['last']): ?>
					<span class="breadcrumbs-split"><i class="icon-right-open"></i></span>
				<?php endif; ?>
				</li>
        <?php endforeach;  } ?>
    </ul>
</div>
<?php endif; ?>
